### ISSUE TITLE
Kafka Connect + Kafka Streams integration using Avro format

### ISSUE THREAD

**Issue by piotr-kalanski** [piotr-kalanski/real-time-data-pipelines-example#1]
- Kafka Connect generates avro schema without namespace (empty Java package)
- Kafka Streams when deserializing needs to have to same package for class
- It's not possible to import class from default package from named package: https://stackoverflow.com/questions/2030148/whats-the-syntax-to-import-a-class-in-a-default-package-in-java

**Comment by piotr-kalanski** [comment]
Solution is to generate with Kafka Connect schema with namespace...

**Comment by piotr-kalanski** [comment]
There is existing issue in Kafka Connect JDBC: https://github.com/confluentinc/kafka-connect-jdbc/issues/123

**Comment by rajak1** [comment]
How does this work if I have a multiple tables in the whitelist? I was expecting one single namespace for all the tables (something like transforms.setSchema.schema.namespace)

**Comment by rksharma82** [comment]
@rajak1 did you find a clue to do this for multiple tables ?

**Comment by aoboturov** [comment]
One could use multiple different multiple independent connectors configured with different namespaces.
